const PROJECTS = [
{"id":"rustania","n":"01","name":"Rustania Homes","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/Rustania.html","images":["PROJECTS/RUSTANIA/A_ExC_001.1.png","PROJECTS/RUSTANIA/A_ExC_001.2.png","PROJECTS/RUSTANIA/A_ExC_002.1.png","PROJECTS/RUSTANIA/A_ExC_002.2.png","PROJECTS/RUSTANIA/A_ExC_003.1.png","PROJECTS/RUSTANIA/A_ExC_003.3.png","PROJECTS/RUSTANIA/A_ExC_004.1.png","PROJECTS/RUSTANIA/A_ExC_005.1.png"]},
{"id":"lean","n":"02","name":"Lean Villa","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/Lean_Villa.html","images":["PROJECTS/Lean_Villa/ExC_01.1.jpg","PROJECTS/Lean_Villa/ExC_02.1.jpg","PROJECTS/Lean_Villa/ExC_05.2.jpg","PROJECTS/Lean_Villa/Lands_01.1.jpg","PROJECTS/Lean_Villa/Liv_01.1.jpg","PROJECTS/Lean_Villa/Liv_04.1.jpg","PROJECTS/Lean_Villa/Din_01.jpg","PROJECTS/Lean_Villa/Altar_01.1.jpg"]},
{"id":"tt","n":"03","name":"T&T Villa","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/TT_Villa.html","images":["PROJECTS/TT_Villa/ExC_01.1.jpg","PROJECTS/TT_Villa/ExC_02.1.jpg","PROJECTS/TT_Villa/ExC_06.1.jpg","PROJECTS/TT_Villa/ExC_01.2.png","PROJECTS/TT_Villa/Livin_01.1.jpg","PROJECTS/TT_Villa/Livin_03.1.jpg","PROJECTS/TT_Villa/Stair_01.1.jpg","PROJECTS/TT_Villa/Pool_02.jpg"]},
{"id":"thudieu","n":"04","name":"Thu Điếu","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/NamThien1.html","images":["PROJECTS/Thu_Dieu/ExC_02.jpg","PROJECTS/Thu_Dieu/ExC_01.2.jpg","PROJECTS/Thu_Dieu/ExC_05.jpg","PROJECTS/Thu_Dieu/Lob_01.jpg","PROJECTS/Thu_Dieu/Liv_01.jpg","PROJECTS/Thu_Dieu/Din_01.jpg","PROJECTS/Thu_Dieu/SHC_01.jpg","PROJECTS/Thu_Dieu/Br1_03.jpg"]},
{"id":"mrdang","n":"05","name":"Mr Đặng Villa","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/SimplePC.html","images":["PROJECTS/SimplePC/Ext_001.3.png","PROJECTS/SimplePC/Ext_003.1.png","PROJECTS/SimplePC/Ext_006.2.png","PROJECTS/SimplePC/KitDin_001.png","PROJECTS/SimplePC/Ya_001.png","PROJECTS/SimplePC/Grand_001.png","PROJECTS/SimplePC/Daun2_003.png","PROJECTS/SimplePC/Gym_001.png"]},
{"id":"tvt","n":"06","name":"TVT Home","type":"Townhouse","page":"https://dreamese.github.io/dreamesestudio/TVT.html","images":["PROJECTS/TVT_House/F1.jpg","PROJECTS/TVT_House/C1.jpg","PROJECTS/TVT_House/LV_1.jpg","PROJECTS/TVT_House/LV_2.jpg","PROJECTS/TVT_House/KC_1.jpg","PROJECTS/TVT_House/B1.jpg","PROJECTS/TVT_House/B2.jpg","PROJECTS/TVT_House/BottomUp.jpg"]},
{"id":"breath","n":"07","name":"Breath Villa","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/Chateur.html","images":["PROJECTS/Chateur_QL_Villa/Chateur_ExC_01.jpg","PROJECTS/Chateur_QL_Villa/Chateur_ExC_02.jpg","PROJECTS/Chateur_QL_Villa/Chateur_ExC_03.jpg","PROJECTS/Chateur_QL_Villa/Chateur_ExC_04.jpg","PROJECTS/Chateur_QL_Villa/Chateur_ExC_05.jpg","PROJECTS/Chateur_QL_Villa/Chateur_ExC_06.jpg","PROJECTS/Chateur_QL_Villa/Chateur_Liv_01.jpg","PROJECTS/Chateur_QL_Villa/Chateur_Din_01.jpg"]},
{"id":"culao","n":"08","name":"Cù Lao Villa","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/TranPhuong.html","images":["PROJECTS/TranPhuong_Villa/TP-Villa_ExC_01.1.png","PROJECTS/TranPhuong_Villa/TP-Villa_ExC_02.1.png","PROJECTS/TranPhuong_Villa/TP-Villa_ExC_03.1.png","PROJECTS/TranPhuong_Villa/TP-Villa_Up_01.1.png","PROJECTS/TranPhuong_Villa/TP-Villa_BH_01.png","PROJECTS/TranPhuong_Villa/TP-Villa_BH_03.1.png","PROJECTS/TranPhuong_Villa/TP-Villa_Lands_01.1.png","PROJECTS/TranPhuong_Villa/TP-Villa_Lands_03.1.png"]},
{"id":"nhuan","n":"09","name":"Nhuận Home","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/PN1.html","images":["PROJECTS/PN1/PN1_ExC_01.1.png","PROJECTS/PN1/PN1_ExC_02.1.png","PROJECTS/PN1/PN1_ExC_03.1.png","PROJECTS/PN1/PN1_ExC_09.1.png","PROJECTS/PN1/PN1_Pool_01.1.png","PROJECTS/PN1/PN1_Terrace_01.png","PROJECTS/PN1/PN1_Liv_01.1.png","PROJECTS/PN1/PN1_Din_01.1.png"]},
{"id":"touch","n":"10","name":"Touch House","type":"Villa","page":"https://dreamese.github.io/dreamesestudio/Touch.html","images":["PROJECTS/TouchHome/ExC_01.1.png","PROJECTS/TouchHome/ExC_02.1.png","PROJECTS/TouchHome/ExC_04.1.png","PROJECTS/TouchHome/Liv_01.1.png","PROJECTS/TouchHome/Liv_04.1.png","PROJECTS/TouchHome/Kitchen_01.1.png","PROJECTS/TouchHome/PN_Bedroom_01.png","PROJECTS/TouchHome/Ms_Bedroom_01.png"]},
{"id":"lavender","n":"11","name":"Lavender Restaurant","type":"Restaurant","page":"https://dreamese.github.io/dreamesestudio/Lavender.html","images":["PROJECTS/Lavender/C1.jpg","PROJECTS/Lavender/C2.jpg","PROJECTS/Lavender/C4.2.jpg","PROJECTS/Lavender/C5.jpg","PROJECTS/Lavender/C6.jpg","PROJECTS/Lavender/C7.jpg","PROJECTS/Lavender/C8.jpg"]},
{"id":"healhill","n":"12","name":"Heal Hill","type":"Bungalow","page":"https://dreamese.github.io/dreamesestudio/Heal_Hill.html","images":["PROJECTS/TN_Cottage/TN_ExC_01.jpg","PROJECTS/TN_Cottage/TN_ExC_02.jpg","PROJECTS/TN_Cottage/TN_ExC_03.jpg","PROJECTS/TN_Cottage/TN_ExC_04.jpg","PROJECTS/TN_Cottage/TN_ExC_05.jpg","PROJECTS/TN_Cottage/TN_Din_01.jpg","PROJECTS/TN_Cottage/TN_Bal_02.jpg","PROJECTS/TN_Cottage/TN_BR1_01.jpg"]},
{"id":"tvn","n":"13","name":"ThanVanNhiep Office","type":"Office","page":"https://dreamese.github.io/dreamesestudio/ThanVanNhiep.html","images":["PROJECTS/ThanVanNhiep/C1.jpg","PROJECTS/ThanVanNhiep/C2.jpg","PROJECTS/ThanVanNhiep/C3.jpg","PROJECTS/ThanVanNhiep/C4.jpg","PROJECTS/ThanVanNhiep/C5.jpg","PROJECTS/ThanVanNhiep/C6.jpg","PROJECTS/ThanVanNhiep/C7.jpg","PROJECTS/ThanVanNhiep/C8.jpg"]},
{"id":"ada","n":"14","name":"Ada Office","type":"Office","page":"https://dreamese.github.io/dreamesestudio/Ada.html","images":["PROJECTS/Ada_Office/Ada_0F_01.png","PROJECTS/Ada_Office/Ada_0F_02.1.png","PROJECTS/Ada_Office/Ada_0F_03.2.png","PROJECTS/Ada_Office/Ada_0F_04.png","PROJECTS/Ada_Office/Ada_0F_05.png","PROJECTS/Ada_Office/Ada_MF_01.2.png","PROJECTS/Ada_Office/Ada_1F_01.png","PROJECTS/Ada_Office/Ada_2F_01.png"]},
{"id":"vsss","n":"15","name":"VSSS","type":"Institutional","page":"projects/vsss.html","local":true,"images":["assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg","assets/vsss-placeholder.svg"]}
];
const BASE='https://dreamese.github.io/dreamesestudio/';
const cards=[...document.querySelectorAll('.project-card')];
const caseStudy=document.getElementById('case-study'),gallery=document.getElementById('caseGallery'),title=document.getElementById('caseTitle'),num=document.getElementById('caseNumber'),viewAll=document.getElementById('viewAllBtn');
let current=0,lbIndex=0;
const src=(p,path)=>(p.local||path.startsWith('assets/'))?path:BASE+path;
function makeShot(p,path,i){const w=document.createElement('div');w.className='case-shot reveal';const f=document.createElement('div');f.className='shot-fallback';f.textContent=String(i+1).padStart(2,'0');w.appendChild(f);const img=document.createElement('img');img.alt=p.name+' — '+String(i+1).padStart(2,'0');img.src=src(p,path);img.onload=()=>f.style.display='none';img.onerror=()=>{img.style.display='none';f.style.display='grid'};w.appendChild(img);w.onclick=()=>{if(img.style.display!=='none')openLb(i)};return w}
function renderCase(i,scroll=true){caseStudy.classList.remove('is-hidden');caseStudy.classList.add('is-open');caseStudy.setAttribute('aria-hidden','false');current=(i+PROJECTS.length)%PROJECTS.length;const p=PROJECTS[current];cards.forEach((c,j)=>c.classList.toggle('active',j===current));num.textContent=p.n+' · '+p.type;title.textContent=p.name;viewAll.href=p.page;viewAll.target=p.local?'_self':'_blank';viewAll.rel=p.local?'':'noopener';gallery.innerHTML='';p.images.forEach((x,j)=>gallery.appendChild(makeShot(p,x,j)));requestAnimationFrame(()=>gallery.querySelectorAll('.reveal').forEach((el,j)=>setTimeout(()=>el.classList.add('visible'),45+j*45)));if(scroll){const h=document.querySelector('.site-header').offsetHeight;window.scrollTo({top:caseStudy.getBoundingClientRect().top+scrollY-h+1,behavior:'smooth'})}}
cards.forEach((c,i)=>c.querySelector('.project-open').onclick=()=>renderCase(i,true));
document.getElementById('prevProject').onclick=()=>!caseStudy.classList.contains('is-hidden')&&renderCase(current-1,false);
document.getElementById('nextProject').onclick=()=>!caseStudy.classList.contains('is-hidden')&&renderCase(current+1,false);
const menu=document.getElementById('menuToggle'),nav=document.getElementById('siteNav');menu.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const progress=document.getElementById('scrollProgress');addEventListener('scroll',()=>{const m=document.documentElement.scrollHeight-innerHeight;progress.style.width=(m>0?scrollY/m*100:0)+'%'},{passive:true});
const navLinks=[...nav.querySelectorAll('a[href^="#"]')];const secObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-40% 0px -50% 0px'});document.querySelectorAll('main section[id]').forEach(s=>secObs.observe(s));
const revObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revObs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.section-title,.project-card,.career>div,.about-data>div').forEach(el=>{el.classList.add('reveal');revObs.observe(el)});
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lbImage');const valid=()=>[...gallery.querySelectorAll('img')].filter(x=>x.style.display!=='none'&&x.src);function showLb(){const a=valid();if(!a.length)return;lbIndex=Math.max(0,Math.min(lbIndex,a.length-1));lbImg.src=a[lbIndex].src;lb.classList.add('open');document.body.style.overflow='hidden'}function openLb(i){const a=valid();lbIndex=Math.min(i,Math.max(0,a.length-1));showLb()}function moveLb(d){const a=valid();if(!a.length)return;lbIndex=(lbIndex+d+a.length)%a.length;showLb()}function closeLb(){lb.classList.remove('open');document.body.style.overflow=''}
document.getElementById('lbClose').onclick=closeLb;document.getElementById('lbPrev').onclick=()=>moveLb(-1);document.getElementById('lbNext').onclick=()=>moveLb(1);lb.onclick=e=>{if(e.target===lb)closeLb()};document.addEventListener('keydown',e=>{if(lb.classList.contains('open')){if(e.key==='Escape')closeLb();if(e.key==='ArrowLeft')moveLb(-1);if(e.key==='ArrowRight')moveLb(1);return}if(e.key==='Escape'&&caseStudy.classList.contains('is-open')){caseStudy.classList.remove('is-open');caseStudy.classList.add('is-hidden');caseStudy.setAttribute('aria-hidden','true');cards.forEach(c=>c.classList.remove('active'))}});
let tx=0;lb.addEventListener('touchstart',e=>tx=e.changedTouches[0].clientX,{passive:true});lb.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-tx;if(Math.abs(dx)>50)moveLb(dx<0?1:-1)},{passive:true});